### ISSUE TITLE
07_DQN.ipynb：CUDA 不能对浮点张量执行位运算

### ISSUE THREAD

**Issue by zmr-233** [Aegis1863/ML_practice#1]
在"强化学习笔记/07_DQN.ipynb"中，In[5]的如下之处：
```python
q_targets = rewards + self.gamma * max_next_q_values * (1 - (dones | truncated))  
```
会有报错RuntimeError: "bitwise_or_cuda" not implemented for 'Float'
因为CUDA 不能对浮点张量执行位运算，可以修改为：
```python
combined = (dones.bool() | truncated.bool()).float()
q_targets = rewards + self.gamma * max_next_q_values * (1 - combined)
```

**Comment by Bowen1911** [comment]
我笔记本代码是前几个月跑的，当时没报错，现在没试过，不过你的改动应该也是可行的👍

**Comment by Bowen1911** [comment]
根据gymnasium的[官方文档](https://gymnasium.farama.org/tutorials/gymnasium_basics/handling_time_limits/)，truncated时应该更新q_targets，但是truncated仍然作为训练终止条件。已更新所有算法相关部分
`q_targets = rewards + self.gamma * max_next_q_values * (1 - (dones | truncated))` 👉 `q_targets = rewards + self.gamma * max_next_q_values * (1 - dones)`
