### ISSUE TITLE
输出层直接使用ReLU可能不是最佳选择

### ISSUE THREAD

**Issue by zmr-233** [Aegis1863/ML_practice#2]
强化学习笔记/09_策略梯度.ipynb中，在In[2]的PolicyNet中使用了：
```python
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return F.softmax(x, dim=1)  # 输出各动作的概率
```
建议移除`x = F.relu(self.fc2(x))`的ReLU激活函数，对于输出层，直接使用ReLU可能不是最佳选择，因为它会产生非负的激活值，出现无法训练的问题，这是图像：
![image](https://github.com/Aegis1863/ML_practice/assets/132034425/d810fed7-33d1-43ff-bc19-899ebb9e0f57)

改为
```python
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.softmax(x, dim=1)  # 输出各动作的概率
```
![image](https://github.com/Aegis1863/ML_practice/assets/132034425/43b2c888-aaaa-4382-98ae-38d07fbc6e1e)

**Comment by Bowen1911** [comment]
确实有问题，已修改
